# Generated by Django 5.1.5 on 2025-01-21 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_produto_mmm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mmm',
            new_name='Produto',
        ),
    ]
