# Generated by Django 5.1.5 on 2025-01-21 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_mmm_produto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
